PREFIX_SETS = {
    "minimal": {
        "en": "The phrase goes: ",
        "de": "Die Redewendung lautet: ",
        "ru": "Выражение звучит так: ",
        "zh": "这个说法是：",
        "ja": "この表現は：",
        "tr": "Bu ifade şöyledir: ",
        "id": "Ungkapan ini adalah: ",
        "ar": "هذه العبارة هي: ",
    },
    "frequency": {
        "en": "The more common way to say it is: ",
        "de": "Die häufigere Art, es zu sagen, lautet: ",
        "ru": "Более распространённый способ сказать это: ",
        "zh": "更常见的说法是：",
        "ja": "より一般的な言い方は：",
        "tr": "Daha yaygın söyleniş şekli şöyledir: ",
        "id": "Cara yang lebih umum untuk mengatakannya adalah: ",
        "ar": "الطريقة الأكثر شيوعًا للتعبير عن ذلك هي: ",
    },
    "discourse": {
        "en": "People always say: ",
        "de": "Man sagt immer: ",
        "ru": "Всегда говорят: ",
        "zh": "大家都说：",
        "ja": "よく言う：",
        "tr": "Hep derler ki: ",
        "id": "Orang selalu bilang: ",
        "ar": "يقولون دائمًا: ",
    },
    "metalinguistic": {
        "en": "In this language, the conventional order for this pair is: ",
        "de": "In dieser Sprache lautet die übliche Reihenfolge dieses Paares: ",
        "ru": "В этом языке привычный порядок для этой пары таков: ",
        "zh": "在这种语言中，这对词的惯用顺序是：",
        "ja": "この言語でこの語の組の慣用的な順序は：",
        "tr": "Bu dilde bu çiftin alışılmış sırası şöyledir: ",
        "id": "Dalam bahasa ini, urutan lazim untuk pasangan ini adalah: ",
        "ar": "في هذه اللغة، الترتيب المعتاد لهذا الزوج هو: ",
    },
}
